import type { Badge, HubUpgrade, TitleDef } from "../types";

export const BADGES: Badge[] = [
  { id: "bdg-cookie", name: "Crumb Analyst", icon: "🍪", description: "Closed the Strange Cookie Incident." },
  { id: "bdg-bench", name: "Bench Certified", icon: "🪑", description: "Identified an anonymous bench-builder without making a fuss." },
  { id: "bdg-plant", name: "Chlorophyll Medic", icon: "🪴", description: "Saved a plant from death by committee." },
  { id: "bdg-keeper", name: "Keyholder", icon: "🔑", description: "Solved a lock that was guarding nothing." },
  { id: "bdg-sign", name: "True North", icon: "🧭", description: "Corrected a sign that had been lying for two years." },
  { id: "bdg-umbrella", name: "Aniseed Tracker", icon: "☂️", description: "Reunited an umbrella with its person." },
  { id: "bdg-chair", name: "Velvet Investigator", icon: "👑", description: "Understood The Chair." },
  { id: "bdg-dog", name: "Biscuit Auditor", icon: "🐕", description: "Exonerated every dog in the district." },
  { id: "bdg-access", name: "Door Opener", icon: "♿", description: "Fixed an accessible entrance that wasn't." },
  { id: "bdg-picnic", name: "Seven Sandwiches", icon: "🧺", description: "Left a perfect picnic perfectly alone." },
  { id: "bdg-operation", name: "Field Operative", icon: "🛠️", description: "Made the real world slightly better." },
  { id: "bdg-first", name: "First Case Closed", icon: "📁", description: "Opened the file. Closed the file." },
  { id: "bdg-builder", name: "HQ Founder", icon: "🏚️", description: "Completed your first hub upgrade." },
  { id: "bdg-crew", name: "Brunch Certified", icon: "🥐", description: "Survived a full Brunch Crew case." },
  { id: "bdg-five", name: "Five Files Deep", icon: "🗂️", description: "Closed five cases." },
];

export const TITLES: TitleDef[] = [
  { id: "ttl-rookie", name: "Provisional Problem Solver", description: "Everyone starts here." },
  { id: "ttl-cookie-auditor", name: "Community Cookie Auditor", description: "Trusted with tins." },
  { id: "ttl-bench-inspector", name: "Bench Inspector General", description: "Sits with authority." },
  { id: "ttl-snack-defender", name: "Defender of the Snack Table", description: "Holds the line at the drawer." },
  { id: "ttl-receipts", name: "Keeper of Extremely Important Receipts", description: "Never throws anything away. Correctly." },
  { id: "ttl-accidental", name: "Most Likely to Solve a Mystery by Accident", description: "It counts." },
  { id: "ttl-plot-twist", name: "Plot Twist Specialist", description: "Saw the frog coming." },
  { id: "ttl-master-detective", name: "Master Detective", description: "Found the smallest fix with the biggest effect." },
  { id: "ttl-evidence-royalty", name: "Evidence Queen", description: "Files beautifully. Theorises wildly." },
  { id: "ttl-chaos-officer", name: "Chief Chaos Officer", description: "Improves things nobody asked about." },
  { id: "ttl-strategist", name: "Snack-Fuelled Strategist", description: "Thinks best mid-pastry." },
];

export const HUB_UPGRADES: HubUpgrade[] = [
  {
    id: "hub-board",
    area: "Mystery Board",
    icon: "🧵",
    name: "String, Pins & Suspicion",
    description: "A corkboard, red string, and the right to point at it dramatically.",
    built: "The board is now covered in string. Nobody understands it except you, which is ideal.",
    cost: { points: 150, materials: { salvage: 1 } },
    unlocks: "Case files display their category and district.",
  },
  {
    id: "hub-lounge",
    area: "Cozy Investigation Lounge",
    icon: "🛋️",
    name: "Two Armchairs & A Lamp",
    description: "Somewhere to sit and be smug about solving things.",
    built: "One mustard armchair, one lamp at exactly the right angle. Thinking capacity: up.",
    cost: { points: 250, materials: { salvage: 2, curios: 1 } },
  },
  {
    id: "hub-garden",
    area: "Community Garden",
    icon: "🌿",
    name: "Raised Beds",
    description: "Four beds, one water butt, zero rota disputes.",
    built: "Beans are happening. Actually happening.",
    cost: { points: 300, materials: { seeds: 3, salvage: 1 } },
    requires: "hub-board",
  },
  {
    id: "hub-snack",
    area: "Snack Station",
    icon: "🥐",
    name: "The Drawer That Works",
    description: "Restocked twice weekly. Opens without a fight.",
    built: "The drawer glides. The breadstick remains. Some traditions survive renovation.",
    cost: { points: 280, materials: { curios: 1, seeds: 1 } },
  },
  {
    id: "hub-workshop",
    area: "Workshop",
    icon: "🔧",
    name: "Bench, Vice & Good Light",
    description: "For fixing things that other people gave up on.",
    built: "Sawdust smell restored. Three benches repaired in the first week.",
    cost: { points: 350, materials: { salvage: 4 } },
    requires: "hub-lounge",
  },
  {
    id: "hub-dog",
    area: "Dog-Friendly Corner",
    icon: "🐾",
    name: "Water Bowl & Shade",
    description: "Plus a jar of biscuits at dog height and a jar at human height.",
    built: "Six regular canine visitors. One of them has business cards. Long story.",
    cost: { points: 220, materials: { curios: 2 } },
  },
  {
    id: "hub-map",
    area: "Adventure Map Wall",
    icon: "🗺️",
    name: "The District Map",
    description: "Every case pinned to where it happened.",
    built: "Three districts mapped. The northeast corner is labelled HERE BE SIGNAGE PROBLEMS.",
    cost: { points: 320, materials: { salvage: 2, curios: 1 } },
    requires: "hub-board",
  },
  {
    id: "hub-museum",
    area: "Community Justice Museum",
    icon: "🏛️",
    name: "Three Display Cases",
    description: "For objects that are unnecessarily complicated, surprisingly useful, or completely ridiculous.",
    built: "Current star exhibit: a ceramic frog on a plinth, donated anonymously.",
    cost: { points: 420, materials: { curios: 4 } },
    requires: "hub-map",
  },
  {
    id: "hub-archive",
    area: "Evidence Archive",
    icon: "🗄️",
    name: "Proper Filing At Last",
    description: "Every closed case, labelled and cross-referenced.",
    built: "Alphabetical. Cross-referenced. Faintly terrifying.",
    cost: { points: 380, materials: { salvage: 2, curios: 2 } },
  },
  {
    id: "hub-shelf",
    area: "Weird Objects Shelf",
    icon: "🔮",
    name: "The Shelf",
    description: "No theme. No criteria. Deeply important.",
    built: "Contains: a conker, a bus ticket, a very small shoe, and something nobody will identify.",
    cost: { points: 200, materials: { curios: 3 } },
  },
  {
    id: "hub-celebration",
    area: "Celebration Area",
    icon: "🎉",
    name: "Bunting & A Small Gong",
    description: "Every closed case deserves a noise.",
    built: "The gong is struck once per solved case. Neighbours have stopped asking.",
    cost: { points: 450, materials: { salvage: 2, seeds: 1, curios: 2 } },
    requires: "hub-snack",
  },
];

export const CREW_AWARDS = [
  "Chief Chaos Officer",
  "Master Detective",
  "Most Suspiciously Good Actor",
  "Snack-Fuelled Strategist",
  "Evidence Royalty",
  "Plot Twist Specialist",
  "Most Likely to Solve a Mystery by Accident",
  "Best Wild Theory",
  "Fastest Improviser",
  "Most Convincing Nonsense",
  "Keeper of Extremely Important Receipts",
  "Defender of the Snack Table",
  "Bench Inspector General",
  "Community Cookie Auditor",
];
